
###
# -*- coding: utf-8 -*-
"""intro-geospatial-data-science-point-polygon-overaly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwE6WRxPsCcnsI8fkKCKrwO9vfOi2RcH
"""

# pip install folium
# alt enter to run

"""## INSTRUCTOR Notebook

## Welcome to Geographic Data Science!
- This morning's goal: introduce concepts, import libraries, what are Geographic Information Systems(GIS), what is geospatial analysis
- This afternoon's goal: work with spatial datasets, mini-spatial project

- **pandas** data frames contain rows of observations or features, and columns of attributes that describe those features
- **geopandas** data frames contain rows of observations or features, with columns of attributes, and one specialized column that stores the geographic attributes of the feature
- this geometry column can contain:
    - coordinate points
    - coordinates that form a line or 'polyline' feature
    - coordinates that form a shape (polygon)

# Overview
## Questions
- How can I view spatial/geographic/geospatial data in Python?
- What are Geographic Information Systems?  

## Objectives
- Basics of spatial and geospatial data science
- Create a spatial/geospatial Python Jupyter notebook
- Create a computational script to display geographic data

# Reminder
###   To run this code in the 'JupyterLab' environment:
- navigate to https://jhub.dartmouth.edu or  https://jupyterlab.dartmouth.edu
- log in with the credentials provided

**Exercise:**
- plot a basic coordinate pair
"""

# import base libraries such as pandas, matplotlib,pyplot, etc

import matplotlib.pyplot as plt

# Define the coordinate (latitude, longitude)
coordinate = (43.704, -72.29127)

# Plot the coordinate using matplotlib
plt.scatter(coordinate[1], coordinate[0], color='blue')  # Longitude first, then Latitude
plt.text(coordinate[1], coordinate[0], '(Point 1)')
plt.show()

"""**Exercise:**

enter the coordinate values from above to define the variable 'coordinate', and then:

Plot using Folium, a Python library with tools to plot coordinates on existing base maps, such as [Open Street Map](https://www.openstreetmap.org/#map=5/39.572/-75.125) ( https://www.openstreetmap.org/#map=5/39.572/-75.125 )

Open a new browser tab and visit https://geojson.io



"""

# Import folium for simple mapping and base map data
import folium

# import spatial and geospatial libraries and tools such as geopandas, folium, shapely

# Define the coordinate (latitude, longitude)
# task, define a coordinate pair, using geojson.io if necessary, and plot that pair on a folium map:
coordinate_pair =  __________

description = ________


#coordinate_pair =  (43.702867708553384, -72.28817508085851)

#description = "Dartmouth"


# Plot the coordinate using folium
# Create a map centered around the coordinate
m = folium.Map(location=coordinate_pair, zoom_start=16)

# Add a marker to the map
folium.Marker(coordinate_pair, popup=description).add_to(m)

m

"""**Exercise**:

Plot a point at the 0,0 mark, with a 'popup' box stating ('equator and prime meridian')

Set the Zoom start to 3 or 4

Answer the following:  

Where is the 0,0 point of the latitude/longitude system? __________

when you click the marker point, what happens/what is displayed? ________
"""

# Define the coordinate pair for the 0, 0 location (latitude, longitude)
# add a description for the point where the equator (0 latitude) meets the prime meridan (0 longitude)
coordinate_pair =  ________
description = _________

#coordinate_pair = 0,0
#description = "equator/prime meridian (0,0)"

# Plot the coordinate using folium
# Create a map centered around the coordinate
m = folium.Map(location=coordinate_pair, zoom_start=4)

# Add a marker to the map
folium.Marker(coordinate_pair, popup=description).add_to(m)

m

"""**Note where 0,0** is on this world map (web mercator projection)

Hanover is at 43.7149125,-72.2727847
This is actually listed as y,x

so, we're 43.7 degreees north of the equator, and -72 degrees west of the prime meridian

**Always** a good idea to check the map location to make sure it is reasonable.  sometimes x and y get transposed, sometimes a minus sign is left off of a coordinate pair value.

### Json and Geojson formats

#### Javascript open notation, "json" is a way to store data


"Geojson" is geographic version of a json file

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          -72.27311795210923,
          43.69651719162417
        ],
        "type": "Point"
      }
    }
  ]
}

Geojson.io is a free tool that can be used to generate geojson text

https://geojson.io/#map=11.1/43.7223/-72.1904

**Exercise**:
Create a point using https://geojson.io and copy the point into the 'geojson_data' variable below.  Run the cell and see if you can produce a map with the point shown at the correct location
"""

import folium
import json
# define location in GeoJSON format(using geojson.io) and extract coordinates data

# copy in spatial data, from a single point created with
# https://geojson.io/


# Note: any well-formatted geojson with a collection of POINT features should work here:
geojson_data =  {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          -72.27311795210923,
          43.69651719162417
        ],
        "type": "Point"
      }
    }
  ]
}

coordinates = geojson_data['features'][0]['geometry']['coordinates']
latitude = coordinates[1]
longitude = coordinates[0]
# visualize: create a map centered around the point, Add the point to the map and display
m = folium.Map(location=[latitude, longitude], zoom_start=15)
folium.Marker([latitude, longitude]).add_to(m)
m
# it is also possible to save the map to an html file, rather than display it in the Jupyter notebook:
# m.save("map.html")

# code-along, type the following:

# assign values for latitude and longitude, a global geospatial addressing system, that uniquely identifies a location
latitude = 43.7031000
longitude = -72.28854
map = folium.Map(location=[latitude, longitude], zoom_start=16)
marker = folium.Marker(location=[latitude,longitude])
marker.add_to(map)
map

#pip install pandas
#pip install geopandas

import pandas as pd

import geopandas as gpd
import shapely

# first, let's read in a CSV file, using the 'pandas' library
points_csv = pd.read_csv("https://rcweb.dartmouth.edu/homes/f002d69/workshops/data/bear-sightings.csv")
points_csv.head(3)

# next, convert the pandas frame to geopandas frame
points = gpd.GeoDataFrame(points_csv, geometry=gpd.points_from_xy(points_csv.longitude, points_csv.latitude))
points.head(2)
# 2025-06-25, had to restart kernel,
# and reinstall and reimport pandas and geopandas

# Set the CRS to EPSG 4326, a worldwide coordinate system
#  (https://epsg.io/4326)
points.set_crs(epsg=4326, inplace=True)
# Verify the CRS
print(points.crs)

zipfile_url="https://rcweb.dartmouth.edu/homes/f002d69/workshops/data/nationalparks_ak.zip"

polygons = gpd.read_file(zipfile_url)

polygons.head(2)









# initiate a folium base map
map = folium.Map(location=[62.6, -148.9], zoom_start=5, control_scale=True)

map

# to get the point data on the map (the CSV), loop over the features in the geopandas 'points' geodataframe
for index, row in points.iterrows():
    folium.CircleMarker(location=[row.latitude,row.longitude],fill=True,fill_opacity=1).add_to(map)

map



# same for polygons / national park boundaries
for index, row in polygons.iterrows():
    folium.GeoJson(row.geometry.__geo_interface__).add_to(map)

map

"""### Spatial Analytics:
#### geospatial analytics...using the 'sjoin' point-in-polygon overlay tool
"""

# spatial/
# https://geopandas.org/en/stable/docs/reference/api/geopandas.sjoin.html
points_in_polygons = gpd.sjoin(points,polygons,predicate='within')

"""### Looking at the data, we should now see point id's joined with polygon data, if the point fell 'within' the polygon"""

points_in_polygons.head(2)

for index, row in points_in_polygons.iterrows():
    folium.CircleMarker(location=[row.latitude,row.longitude], color='gray',fill=True,fill_opacity=1).add_to(map)

# plot the points 'within' using gray, other points blue
map

###


# -*- coding: utf-8 -*-
"""Intro Geospatial Data Science - student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qG0EFPiQsncU3nhUO4WY5KqZs2brdeRy

## Welcome to Geographic Data Science!
### Geographic Information Systems, GIS, Geospatial analysis
- This morning's goal: introduce concepts, import libraries
- This afternoon's goal: work with spatial datasets, mini-spatial project
"""

# version 2025.07.07
# updated July 8 2025
import pandas as pd
import os

"""- pandas data frames contain rows of observations or features, and columns of attributes that describe those features
- **geopandas** data frames contain rows of observations or features, with columns of attributes, and one specialized column that stores the geographic attributes of the feature
- this **geometry** column can contain:
    - coordinate points
    - coordinates that form a line or 'polyline' feature
    - coordinates that form a shape (polygon)
"""

# plot a basic coordinate pair

import matplotlib.pyplot as plt

# define the coordinate pair
coordinates = (43.704, -72.29127)

# Plot the coordinate using matplotlib
plt.scatter(coordinates[1], coordinates[0], color='blue')  # Longitude first, then Latitude
plt.text(coordinates[1], coordinates[0], '(Point 1)')
plt.show()

"""Exercise:
Visit the "Folium" website [https://pypi.org/project/folium/](https://pypi.org/project/folium/) and answer the question: What is this Python library designed to do? ___ ___ ___ ___

"""

# import the folium library here:
import _____________

"""**Exercise**:

enter the coordinate values from above to define the variable 'coordinate', and then:

Plot using Folium, a Python library with tools to plot coordinates on existing base maps, such as [Open Street Map](https://www.openstreetmap.org/#map=5/39.572/-75.125) ( https://www.openstreetmap.org/#map=5/39.572/-75.125 )
"""

# pip install folium

# Import folium for simple mapping and base map data
import folium

# Define the coordinate (latitude, longitude)
coordinates =  ______________

# Plot the coordinate using folium
# Create a map centered around the coordinate
m = folium.Map(location=coordinates, zoom_start=16)

# Add a marker to the map
folium.Marker(coordinates, popup='Point 1').add_to(m)

m

"""**Exercise**:

Plot a point with a 'popup' box at the equator

Answer the following:  when you click the marker point, what happens/what is displayed? ___ ___ ____ ____
"""

# 'json' is an open data format that is very useful in data science
# import the 'json library here:


import _________

# 'geojson' is a special format of json, built for use in geospatial data science, https://pypi.org/project/geojson/

# import the 'geojson library here:

#pip install geojson

import _________



import folium
import json
# define location in GeoJSON format(using geojson.io) and extract coordinates data

# copy in spatial data, from a single point created with
# https://geojson.io/

geojson_data =  ________

coordinates = geojson_data['features'][0]['geometry']['coordinates']
latitude = coordinates[1]
longitude = coordinates[0]
# visualize: create a map centered around the point, Add the point to the map and display
m = folium.Map(location=[____, _____], zoom_start=15)
folium.Marker([_____, ______]).add_to(m)
m
# it is also possible to save the map to an html file, rather than display it in the Jupyter notebook:
# m.save("map.html")

import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)

#pip install geopandas

"""## Exercise:
extract and load a geospatial dataset using the 'GeoPandas' library
"""

import geopandas as gpd
from shapely.geometry import Point

# List of cities with their coordinates
cities = {
    'City': ['Boston', 'New York', 'Washington D.C.'],
    'Latitude': [42.3601, 40.7128, 38.9072],
    'Longitude': [-71.0589, -74.0060, -77.0369]
}

# Creating a GeoDataFrame
geometry = [Point(xy) for xy in zip(cities['Longitude'], cities['Latitude'])]
geo_df = gpd.GeoDataFrame(cities, geometry=geometry)

print(geo_df)

# Initialize a map centered on the northeastern US
m = folium.Map(location=[41, -74], zoom_start=6)

# Add points to the map
for idx, row in geo_df.iterrows():
    folium.Marker([row['Latitude'], row['Longitude']], popup=row['City']).add_to(m)

# Display the map
m

path = os.getcwd()
print(path)

# for jhub 2025-07-07:

# %%
path = os.getcwd()

# %%
print(path)

# %%
animal_sightings_df = pd.read_csv('/home/jovyan/shared/DSS/day7-am/data/animal-sightings.csv')
animal_sightings_df.head(3)

import matplotlib.pyplot as plt

# %%

plt.scatter(animal_sightings_df['longitude'], animal_sightings_df['latitude'], alpha=0.5, edgecolors='w', s=100)
# Show the plot
plt.show()

import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
import folium

# use geojson.io to get the remaining state capitals for Maine, NH, VT,

# Define a dictionary with state capitals
state_capitals = {
    __________________,
    'New Hampshire': {'city': 'Concord', 'lat': 43.2109, 'lon': -71.5323},
    ____________________,
    'Massachusetts': {'city': 'Boston', 'lat': 42.3584, 'lon': -71.0596},
    ____________________,
    'Connecticut': {'city': 'Hartford', 'lat': 41.7654, 'lon': -72.6770}
}

# Create a list to store the GeoDataFrame rows
data = []

# Iterate over the state capitals dictionary
for state, info in state_capitals.items():
    # Create a Point object using the latitude and longitude
    point = Point(info['lon'], info['lat'])

    # Append a dictionary with the state, city, and point to the data list
    data.append({
        'State': state,
        'City': info['city'],
        'geometry': point
    })

# Convert the data list to a GeoDataFrame
gdf = gpd.GeoDataFrame(data, geometry='geometry', crs='EPSG:4326')

# Print the GeoDataFrame
print(gdf)

# Create a Folium map with the state capitals
map = folium.Map(location=[44.0042, -71.3333], zoom_start=7)

# Iterate over the GeoDataFrame rows and add markers to the map
# use the correct fields for the popup
for index, row in gdf.iterrows():
    folium.Marker(
        location=[row['geometry'].y, row['geometry'].x],
        popup=f"{row[_________]}: {row[_____]}"
    ).add_to(map)

# Save the map as an HTML file
#map.save('new_england_state_capitals.html')
#show the map
map

# geocode a street address
from geopy.geocoders import Nominatim

# Instantiate the Nominatim geolocator
geolocator = Nominatim(user_agent="my_geocoder_app") # Replace with a unique user agent

# Geocode an address
address = "1600 Amphitheatre Parkway, Mountain View, CA"
location = geolocator.geocode(address)

if location:
    print(f"Address: {location.address}")
    print(f"Latitude: {location.latitude}")
    print(f"Longitude: {location.longitude}")
else:
    print("Address not found.")

map = folium.Map(location=[location.latitude, location.longitude], zoom_start=15)
folium.Marker([location.latitude, location.longitude], popup=address).add_to(map)
map
